export { ReactComponent as UserIcon } from './accountbox_icon.svg'
export { ReactComponent as UserIcon2 } from './accountcircle_icon.svg'
export { ReactComponent as KeyIcon } from './key_icon.svg'
export { ReactComponent as KeyIcon2 } from './keyitem_icon.svg'
export { ReactComponent as AddIcon } from './add_btn.svg'
export { ReactComponent as AddIcon2 } from './add_btn2.svg'

export { default as post } from './post_btn.svg'
export { default as chat } from './msg_btn.svg'
export { default as question } from './que_btn.svg'
export { default as schedule } from './cal_btn.svg'
export { default as mission } from './mission_btn.svg'
export { default as task } from './task_btn.svg'
export { default as setting } from './set_btn.svg'
export { default as prof } from './proficon.png'

export { ReactComponent as Post } from './post_btn.svg'
export { ReactComponent as Chat } from './msg_btn.svg'
export { ReactComponent as Question } from './que_btn.svg'
export { ReactComponent as Schedule } from './cal_btn.svg'
export { ReactComponent as Mission } from './mission_btn.svg'
export { ReactComponent as Task } from './task_btn.svg'
export { ReactComponent as Setting } from './set_btn.svg'
export { ReactComponent as Exit } from './exit_btn.svg'

export { default as noimage } from './noimage.png'
export { default as mail } from './mail-24px.svg'
export { default as send } from './send_btn.svg'
